# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "turtlebot3"
  fleet_manager:
    prefix: "http://127.0.0.1:22017"
    ip: "127.0.0.1"
    port: 22017
    user: "some_user"
    password: "some_password"   
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: False
    clean: False
    finishing_request: "park" # [park, charge, nothing]
  actions: ["teleop"]

  responsive_wait: True # Should responsive wait be on/off for the whole fleet by default? False if not specified.

# turtlebot3 CONFIG =================================================================
robots:
  turtlebot3_1:
    robot_config:
      max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 1.0
      charger:
        waypoint: "turtlebot3_charger_1"
      start:
        map_name: "L1"
        waypoint: "turtlebot3_charger_1"
        orientation: 0.0 # radians

# TRANSFORM CONFIG =============================================================
# For computing transforms between Robot and RMF coordinate systems

# Optional
reference_coordinates:
  rmf: [[0.0, 0.0],
        [14.9834, 0.0],
        [14.9834, -5.5079],
        [0.0, -5.5079]]
  robot: [[ -7.311037063598633, 1.4209141731262207],
          [ 8.718361854553223, 1.4333285093307495],
          [ 8.712226867675781, -4.453343868255615],
          [ -7.3213982582092285, -4.454360485076904]]